import { Patient, Alert } from './types';

export const samplePatients: Patient[] = [
  {
    id: 'p1',
    name: 'Sita Sharma',
    age: 28,
    gravida: 2,
    para: 1,
    lmpDate: '2025-06-01',
    gestationalAge: 32,
    village: 'Bhaktapur Ward 5',
    phone: '+977-9841234567',
    fchvAssigned: 'Radha Thapa',
    registrationDate: '2025-08-15',
    visits: [
      {
        id: 'v1',
        patientId: 'p1',
        visitNumber: 1,
        date: '2025-10-15',
        gestationalAge: 20,
        visitType: 'Routine',
        systolic: 120,
        diastolic: 80,
        weight: 58,
        fundalHeight: 20,
        proteinuria: 'Negative',
        edema: 'None',
        headache: 'None',
        visualDisturbances: false,
        epigastricPain: false,
        fetalMovement: 'Normal',
        clinicalNotes: 'Normal routine visit. All parameters within normal range.',
        riskScore: 0,
        riskLevel: 'LOW',
      },
      {
        id: 'v2',
        patientId: 'p1',
        visitNumber: 2,
        date: '2025-11-26',
        gestationalAge: 26,
        visitType: 'Routine',
        systolic: 135,
        diastolic: 85,
        weight: 61,
        fundalHeight: 25,
        proteinuria: 'Trace',
        edema: 'Mild (feet only)',
        headache: 'Mild',
        visualDisturbances: false,
        epigastricPain: false,
        fetalMovement: 'Normal',
        clinicalNotes: 'Slight increase in BP. Mild edema noted. Continue monitoring.',
        riskScore: 25,
        riskLevel: 'LOW',
      },
      {
        id: 'v3',
        patientId: 'p1',
        visitNumber: 3,
        date: '2026-01-07',
        gestationalAge: 32,
        visitType: 'Follow-up',
        systolic: 155,
        diastolic: 95,
        weight: 64,
        fundalHeight: 30,
        proteinuria: '2+',
        edema: 'Severe (face and hands)',
        headache: 'Severe/persistent',
        visualDisturbances: true,
        epigastricPain: false,
        fetalMovement: 'Normal',
        clinicalNotes: 'Significant BP elevation. Severe edema and headache. Visual disturbances reported. Urgent referral recommended.',
        riskScore: 85,
        riskLevel: 'HIGH',
      },
    ],
  },
  {
    id: 'p2',
    name: 'Maya Tamang',
    age: 24,
    gravida: 1,
    para: 0,
    lmpDate: '2025-08-15',
    gestationalAge: 28,
    village: 'Lalitpur Ward 3',
    phone: '+977-9851234568',
    fchvAssigned: 'Radha Thapa',
    registrationDate: '2025-10-01',
    visits: [
      {
        id: 'v4',
        patientId: 'p2',
        visitNumber: 1,
        date: '2025-11-15',
        gestationalAge: 13,
        visitType: 'Routine',
        systolic: 110,
        diastolic: 70,
        weight: 52,
        fundalHeight: 13,
        proteinuria: 'Negative',
        edema: 'None',
        headache: 'None',
        visualDisturbances: false,
        epigastricPain: false,
        fetalMovement: 'Normal',
        clinicalNotes: 'First visit. All normal.',
        riskScore: 0,
        riskLevel: 'LOW',
      },
      {
        id: 'v5',
        patientId: 'p2',
        visitNumber: 2,
        date: '2026-01-15',
        gestationalAge: 22,
        visitType: 'Routine',
        systolic: 115,
        diastolic: 75,
        weight: 55,
        fundalHeight: 22,
        proteinuria: 'Negative',
        edema: 'None',
        headache: 'None',
        visualDisturbances: false,
        epigastricPain: false,
        fetalMovement: 'Normal',
        clinicalNotes: 'Routine follow-up. All normal.',
        riskScore: 0,
        riskLevel: 'LOW',
      },
    ],
  },
  {
    id: 'p3',
    name: 'Kamala Rai',
    age: 32,
    gravida: 3,
    para: 2,
    lmpDate: '2025-09-01',
    gestationalAge: 24,
    village: 'Kathmandu Ward 12',
    phone: '+977-9861234569',
    fchvAssigned: 'Radha Thapa',
    registrationDate: '2025-11-01',
    visits: [
      {
        id: 'v6',
        patientId: 'p3',
        visitNumber: 1,
        date: '2025-12-01',
        gestationalAge: 13,
        visitType: 'Routine',
        systolic: 140,
        diastolic: 90,
        weight: 68,
        fundalHeight: 13,
        proteinuria: '1+',
        edema: 'Mild (feet only)',
        headache: 'Moderate',
        visualDisturbances: false,
        epigastricPain: false,
        fetalMovement: 'Normal',
        clinicalNotes: 'Elevated BP noted. Mild proteinuria. Needs close monitoring.',
        riskScore: 50,
        riskLevel: 'MODERATE',
      },
    ],
  },
];

export const sampleAlerts: Alert[] = [
  {
    id: 'a1',
    patientId: 'p1',
    patientName: 'Sita Sharma',
    message: 'Risk escalated from LOW to HIGH — urgent referral recommended',
    type: 'escalation',
    date: '2026-01-07',
  },
  {
    id: 'a2',
    patientId: 'p3',
    patientName: 'Kamala Rai',
    message: 'Follow-up visit due — moderate risk patient',
    type: 'followup',
    date: '2026-01-10',
  },
  {
    id: 'a3',
    patientId: 'p2',
    patientName: 'Maya Tamang',
    message: 'Routine follow-up visit due',
    type: 'followup',
    date: '2026-01-15',
  },
];
